### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
### code here
import numpy as np

# Define the array with NaN values
array = np.array([[3., 2., np.nan, 1.],
                  [10., 12., 10., 9.],
                  [5., np.nan, 1., np.nan]])

# Print the original array
print("Original array:")
print(array)

# Find the missing data (NaN values)
missing_data = np.isnan(array)

# Print the result
print("Find the missing data of the said array:")
print(missing_data)


Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]
Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [2]:
### code here
import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([1, 2, 3, 4])

# Check if the two arrays are equal element-wise
are_equal = np.array_equal(array1, array2)
print("Are the two arrays equal element-wise?")
print(are_equal)

# Check element-wise equality
element_wise_comparison = array1 == array2
print("\nElement-wise comparison:")
print(element_wise_comparison)


Are the two arrays equal element-wise?
True

Element-wise comparison:
[ True  True  True  True]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [3]:
## code here
import numpy as np

# Create a 4x4 array with random values
original_array = np.random.randint(0, 20, size=(4, 4))

# Print the original array
print("Original array:")
print(original_array)

# Swap the first and last rows
new_array = original_array.copy()  # Create a copy to preserve the original array
new_array[[0, -1]] = new_array[[-1, 0]]

# Print the new array after swapping rows
print("\nNew array after swapping first and last rows of the said array:")
print(new_array)


Original array:
[[13 18  2  0]
 [ 2 17  9  3]
 [ 5 15 15  6]
 [14 17  6  6]]

New array after swapping first and last rows of the said array:
[[14 17  6  6]
 [ 2 17  9  3]
 [ 5 15 15  6]
 [13 18  2  0]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [4]:
#### code here
import numpy as np

# Sample list and tuple
my_list = [1, 2, 3, 4]
my_tuple = (5, 6, 7, 8)

# Convert list and tuple to arrays
array_from_list = np.array(my_list)
array_from_tuple = np.array(my_tuple)

# Print the resulting arrays
print("Array from list:", array_from_list)
print("Array from tuple:", array_from_tuple)

Array from list: [1 2 3 4]
Array from tuple: [5 6 7 8]


###### 5. Write a NumPy program to find common values between two arrays.

In [5]:
### code here
import numpy as np

# Define the two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 5, 6, 7, 8])

# Find the common values
common_values = np.intersect1d(array1, array2)

# Print the common values
print("Common values between the two arrays:", common_values)

Common values between the two arrays: [3 5]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [6]:
### code here
import numpy as np

# Create a 1-D array with 6 elements
arr = np.arange(1, 7)

# Reshape to 3x2
new_arr1 = arr.reshape(3, 2)

# Reshape to 2x3
new_arr2 = arr.reshape(2, 3)

# Print the reshaped arrays
print("Reshape 3x2:")
print(new_arr1)
print("\nReshape 2x3:")
print(new_arr2)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]

Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [7]:
### code here
import numpy as np

# Sample array
arr = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

# Get unique values and their frequencies
unique_values, counts = np.unique(arr, return_counts=True)

# Print the results
print("Original array:")
print(arr)
print("\nFrequency of unique values of the said array:")
print(np.asarray((unique_values, counts)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]

Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [8]:
### code here
import numpy as np

# Define two arrays with different shapes
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]])
q = np.array([10, 11, 12])

# Perform broadcasting (addition in this case)
result = p + q

# Print the original arrays and the result
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
print(result)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

In [9]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [10]:
## code here
import numpy as np

# Create a 4x4 array
arr = np.arange(16).reshape((4, 4))

# Extract third and fourth elements of the first and second rows
extracted_data = arr[:2, 2:4]

# Print the original array and the extracted data
print("Original array:")
print(arr)
print("\nExtracted data: Third and fourth elements of the first and second rows")
print(extracted_data)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [11]:
### code here
from datetime import date, timedelta

# Get today's date
today = date.today()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-07-22
Today: 2024-07-23
Tomorrow: 2024-07-24


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [12]:
## code here
from datetime import date, timedelta

# Start with the first day of May 2017
day = date(2017, 5, 1)

# Find the first Monday
while day.weekday() != 0:  # 0 represents Monday
    day += timedelta(days=1)

# Print the result
print("First Monday in May 2017:")
print(day)

First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
