### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [2]:
### code here
import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)
print("An array of 10 zeros:")
print(zeros_array)

# Create an array of 10 ones
ones_array = np.ones(10)
print("\nAn array of 10 ones:")
print(ones_array)

# Create an array of 10 fives
fives_array = np.full(10, 5)  # Using np.full to create an array with a specific value
print("\nAn array of 10 fives:")
print(fives_array)







An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [ ]:
### code here

In [3]:
### sample output
import numpy as np

# Create an array of integers from 30 to 70
array = np.arange(30, 71)  # The upper limit is exclusive, so use 71 to include 70
print("Array of the integers from 30 to 70:")
print(array)


Array of the integers from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [ ]:
### code here

In [4]:
## sample output
import numpy as np

# Create an array of even integers from 10 to 50
even_array = np.arange(10, 51, 2)
print("Array of even integers from 10 to 50:")
print(even_array)


Array of even integers from 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
### code here

In [5]:
## sample output
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:")
print(identity_matrix)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [ ]:
### code here

In [6]:
## sample output
import numpy as np

# Generate a random number between 0 and 1
random_number = np.random.rand()
print("Random number between 0 and 1:")
print(random_number)

Random number between 0 and 1:
0.30600763098323736


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [ ]:
## code here

In [7]:
## sample output
import numpy as np

# Generate an array of 15 random numbers from a standard normal distribution
random_array = np.random.randn(15)
print("Array of 15 random numbers from a standard normal distribution:")
print(random_array)

Array of 15 random numbers from a standard normal distribution:
[-0.31530015 -0.79831293 -1.04375024  0.77351437 -0.5151657  -1.47410606
 -1.24570403 -0.40235058  0.13774173  1.04776297  0.31309049 -0.00599337
 -1.61316218 -1.83347727 -0.65689203]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [8]:
## code here
import numpy as np

# Create a 3x4 array
array = np.array([[10, 11, 12, 13],
                  [14, 15, 16, 17],
                  [18, 19, 20, 21]])

# Print the original array
print("Original array:")
print(array)

# Iterate over the array and print each element
print("\nEach element of the array is:")
for row in array:
    for element in row:
        print(element, end=' ')



Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [ ]:
## sample output


Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [9]:
## code here
import numpy as np

# Define the two vectors
vector1 = np.array([1, 8, 3, 5])
vector2 = np.array([10, 1, 4, 10])

# Print the vectors
print("Vector-1")
print(vector1)
print("Vector-2")
print(vector2)

# Multiply the values of the two vectors element-wise
result = vector1 * vector2

# Print the result
print("Multiply the values of two said vectors:")
print(result)


Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [10]:
### code here
import numpy as np

# Define the original array
original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

# Print the original array
print("Original array:")
print(original_array)

# Reverse the array
reversed_array = original_array[::-1]

# Print the reversed array
print("Reverse array:")
print(reversed_array)


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [11]:
## code here
import numpy as np

# Define the diagonal elements
diagonal_elements = np.array([1, 2, 3, 4, 5])

# Create the 5x5 matrix with the specified diagonal elements
matrix = np.diag(diagonal_elements)

# Print the matrix
print(matrix)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [12]:
## code here
import numpy as np

# Define the array
array = np.array([[0, 1],
                  [2, 3]])

# Print the original array
print("Original array:")
print(array)

# Compute the sum of all elements
total_sum = np.sum(array)
print("Sum of all elements:")
print(total_sum)

# Compute the sum of each column
sum_columns = np.sum(array, axis=0)
print("Sum of each column:")
print(sum_columns)

# Compute the sum of each row
sum_rows = np.sum(array, axis=1)
print("Sum of each row:")
print(sum_rows)


Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [13]:
## code here
import numpy as np

# Define the two vectors
vector1 = np.array([4, 5])
vector2 = np.array([7, 10])

# Print the original vectors
print("Original vectors:")
print(vector1)
print(vector2)

# Compute the inner product
inner_product = np.dot(vector1, vector2)

# Print the result
print("Inner product of said vectors:")
print(inner_product)


Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
